env:
  global:
    - secure: FMIb2m6XcZI4lMlJlpZuLIIxFynbGX+4VPpBG9jmzHhkjOYqt018Yd6Z2fEz7SAAbO8sUF2mMh0KRXzp8HBaBgD1cO65rOrLXoYwDk0ZLr2GrNd0w6+VrueLUbXl/odAkacWtfzFb6n5MUSJ4wpegk8gPlqf8QojfZGgoXD+qQE=

language: rust
rust: nightly

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose
  - cargo doc --verbose

after_success:
  - cp -R target/doc doc
  - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | /bin/sh
  - rm -r doc
